"""
Partner/Leverancier Profielen — Verrijkt met podcasts, trendwatcher quotes, top 3 producten, evenementen.
"""
from fastapi import APIRouter

partner_router = APIRouter(prefix="/partners", tags=["Partner Profielen"])

PARTNER_PROFILES = {
    "ticra-outdoor": {
        "id": "ticra-outdoor",
        "name": "Ticra Outdoor",
        "tagline": "Outdoor & Wellness products voor recreatie en hospitality",
        "description": "Ticra Outdoor is de toonaangevende leverancier van outdoor wellness producten in de Benelux. Met een uitgebreid assortiment van hottubs, buitensauna's en buitendouches voorzien zij recreatieparken, glamping resorts en vakantieparken van premium wellness faciliteiten. Alle producten worden geleverd met professionele installatie en onderhoud.",
        "website": "https://www.ticraoutdoor.com",
        "logo": "https://www.ticraoutdoor.com/nl/assets/images/ticra-outdoor-logo.svg",
        "hero_image": "https://www.ticraoutdoor.com/nl/assets/galleries/126/_thumbs/medium_327_1_ticra_outdoor_hot_tub_flevoland_skargards_rojal_190_dualburn_1.webp",
        "categorieen": ["hottubs", "buitensaunas", "buitendouches"],
        "pleisureworld_partner": True,
        "pleisureworld_badge": "Preferred Partner",
        "pleisureworld_sinds": "2024",
        "blog_url": "https://www.pleisureworld.nl/blog/ticra-outdoor-wellness-trends",
        "blog_titel": "Wellness op het recreatiepark: de trends van 2026",
        "podcast": {
            "titel": "Leisure Talk #14 — Wellness als verdienmodel",
            "beschrijving": "Richard Otten (Trendwatcher Recreatie) in gesprek met Ticra Outdoor over de groeiende vraag naar wellness op recreatieparken en hoe parkeigenaren hun omzet kunnen verhogen met hottubs en sauna's.",
            "url": "https://www.pleisureworld.nl/podcast/leisure-talk-14",
            "duur": "38 min",
            "gast": "Richard Otten — Trendwatcher Recreatie & Hospitality",
        },
        "trendwatcher_quote": {
            "tekst": "Wellness is geen luxe meer, het is een verwachting. Gasten kiezen een park op basis van de ervaring — en een hottub of sauna bij het chalet maakt het verschil tussen een 7 en een 9 op de review. Ticra begrijpt dat als geen ander.",
            "auteur": "Richard Otten",
            "functie": "Trendwatcher Recreatie & Hospitality",
        },
        "stats": {
            "parken_actief": "120+",
            "jaren_ervaring": "15+",
            "producten_geinstalleerd": "2.500+",
            "klanttevredenheid": "4.8/5",
        },
        "deelname": [
            {"event": "Vakantiebeurs Utrecht 2026", "type": "Exposant"},
            {"event": "Glamping Show 2025", "type": "Keynote Speaker"},
            {"event": "HISWA te Water 2025", "type": "Exposant"},
            {"event": "Pleisureworld Summit 2026", "type": "Preferred Partner"},
        ],
        "top_producten": [
            {
                "id": "well-hottub-basis",
                "name": "TICRA Hottub Houtgestookt",
                "prijs": 2995,
                "image": "https://www.ticraoutdoor.com/nl/assets/galleries/133/_thumbs/medium_409_1_ticra_outdoor_hottub_hout_interne_kachel_welltub_160.webp",
                "reden": "Meest gekozen — Perfecte prijs/kwaliteit voor verhuur",
                "configuraties": 847,
            },
            {
                "id": "well-sauna-barrel",
                "name": "Barrel Sauna Thermowood",
                "prijs": 5495,
                "image": "https://www.ticraoutdoor.com/nl/assets/galleries/97/_thumbs/medium_25-4-buitensauna-barrel-thermowood-ticra-outdoor.webp",
                "reden": "Populairste sauna — Authentieke uitstraling, laag onderhoud",
                "configuraties": 623,
            },
            {
                "id": "well-douche-sunlight",
                "name": "Sunlight Buitendouche",
                "prijs": 695,
                "image": "https://www.ticraoutdoor.com/nl/assets/galleries/141/_thumbs/medium_478_2_buitendouche_red_cedar_sunlightshower_ticra_outdoor_dundalk.webp",
                "reden": "Best seller — Compacte toevoeging bij elke hottub",
                "configuraties": 1204,
            },
        ],
        "usps": [
            "Gratis bezorging bij recreatieparken",
            "2 jaar volledige garantie",
            "Professionele installatie inbegrepen",
            "24/7 service voor recreatiepartners",
            "Leaseconstructies beschikbaar",
        ],
    },
    "kunert-group": {
        "id": "kunert-group",
        "name": "Kunert Group",
        "tagline": "Toonaangevende fabrikant van chalets in Europa sinds 1997",
        "description": "Kunert Mobile Homes is een toonaangevende fabrikant van stacaravans en chalets in Polen en Europa. Met meer dan 25 jaar ervaring produceren zij jaarrondhuizen in vele varianten. Het bedrijf begon in 1997 als importeur van Nederlandse huizen en breidde in 2013 uit naar zelfstandige productie. Kunert levert chalets in 8 landen met eigen transport door heel Europa.",
        "website": "https://www.chaletskunert.nl",
        "logo": "https://chaletskunert.nl/wp-content/uploads/2023/11/cropped-white-2-1-768x52-1.webp",
        "hero_image": "https://chaletskunert.nl/wp-content/uploads/slider/cache/596c295a46e6a41280859315325ba1bc/Image1.png",
        "categorieen": ["chalets", "stacaravans", "sanitair units"],
        "pleisureworld_partner": True,
        "pleisureworld_badge": "Preferred Partner",
        "pleisureworld_sinds": "2023",
        "blog_url": "https://www.pleisureworld.nl/blog/kunert-chalets-modulair-bouwen",
        "blog_titel": "Modulair bouwen: hoe Kunert Group de chaletmarkt verandert",
        "podcast": {
            "titel": "Leisure Talk #8 — De Europese chaletmarkt in beweging",
            "beschrijving": "Een gesprek over hoe Kunert Group vanuit Polen de Nederlandse en Europese markt bedient met innovatieve, betaalbare chalets. Over schaalvoordelen, maatwerk en de toekomst van modulaire vakantiewoningen.",
            "url": "https://www.pleisureworld.nl/podcast/leisure-talk-8",
            "duur": "42 min",
            "gast": "Kunert Group Management — Europees Chaletfabrikant",
        },
        "trendwatcher_quote": {
            "tekst": "De chaletmarkt verschuift van standaard naar premium. Parkeigenaren die investeren in kwalitatieve, jaarronde chalets zien hun bezettingsgraad met 20-30% stijgen. Kunert speelt hier slim op in met hun Premium-lijn — betaalbare luxe, direct leverbaar.",
            "auteur": "Richard Otten",
            "functie": "Trendwatcher Recreatie & Hospitality",
        },
        "stats": {
            "parken_actief": "200+",
            "jaren_ervaring": "27+",
            "producten_geinstalleerd": "10.000+",
            "klanttevredenheid": "4.6/5",
        },
        "deelname": [
            {"event": "Vakantiebeurs Utrecht 2026", "type": "Exposant"},
            {"event": "Recron Jaarcongres 2025", "type": "Partner"},
            {"event": "Holiday & Leisure Expo 2025", "type": "Exposant"},
            {"event": "Pleisureworld Summit 2026", "type": "Preferred Partner"},
        ],
        "top_producten": [
            {
                "id": "kunert-haven",
                "name": "Haven",
                "prijs": 74950,
                "image": "https://chaletskunert.nl/wp-content/uploads/slider/cache/596c295a46e6a41280859315325ba1bc/Image1.png",
                "reden": "Meest gekozen — Modern design, open keuken, ideaal voor verhuur",
                "configuraties": 312,
            },
            {
                "id": "kunert-plat-18",
                "name": "Plat 18",
                "prijs": 89500,
                "image": "https://chaletskunert.nl/wp-content/uploads/slider/cache/a7d32cf654945640a6ba12c117e735de/13-scaled-1.webp",
                "reden": "Premium bestseller — Ruim, 3 slaapkamers, plat dak",
                "configuraties": 245,
            },
            {
                "id": "kunert-plat-12",
                "name": "Plat 12",
                "prijs": 59950,
                "image": "https://chaletskunert.nl/wp-content/uploads/slider/cache/9bb15a9fd5ca8225826fd1bd0d3c2b44/w2.webp",
                "reden": "Budget favoriet — Compact, modern, snel leverbaar",
                "configuraties": 189,
            },
        ],
        "usps": [
            "Fabrieksgarantie 2 jaar (verlengbaar tot 5 jaar)",
            "10 jaar garantie op gegalvaniseerd chassis",
            "Eigen transport door heel Europa",
            "Volledig maatwerk mogelijk",
            "3D Matterport tours beschikbaar",
            "Levertijd slechts 5 weken",
        ],
    },
    "arcabo": {
        "id": "arcabo",
        "name": "Arcabo",
        "tagline": "Al bijna 30 jaar Europa's grootste specialist in chaletbouw",
        "description": "ARCABO is een van de grootste producenten van wintervaste chalets in Europa. Met bijna 30 jaar ervaring brengen zij dagelijks een groot team experts samen om tot in de kleinste details de mooiste chalets te bouwen. ARCABO begeleidt zowel particulieren als recreatieondernemers van planning tot uitvoering, met een eigen showroom en geavanceerde 3D-ontwerpmogelijkheden.",
        "website": "https://www.arcabo.nl",
        "logo": "https://www.arcabo.nl/wp-content/themes/arcabo/library/images/arcabo-logo.svg",
        "hero_image": "https://arcabo.nl/wp-content/uploads/1-New-Bay-A-buitenzijde-2024.png",
        "categorieen": ["chalets", "wintervaste chalets", "recreatie"],
        "pleisureworld_partner": True,
        "pleisureworld_badge": "Preferred Partner",
        "pleisureworld_sinds": "2024",
        "blog_url": "https://www.pleisureworld.nl/blog/arcabo-wintervaste-chalets",
        "blog_titel": "Wintervaste chalets: jaarrond rendement voor parkeigenaren",
        "podcast": {
            "titel": "Leisure Talk #11 — Design als onderscheidend vermogen",
            "beschrijving": "Arcabo over hoe design en kwaliteit het verschil maken in de recreatiemarkt. Over hun showroom, het 3D-ontwerpproces en waarom steeds meer parken kiezen voor wintervaste chalets met een uniek karakter.",
            "url": "https://www.pleisureworld.nl/podcast/leisure-talk-11",
            "duur": "35 min",
            "gast": "Arcabo Design Team — Europa's chaletspecialist",
        },
        "trendwatcher_quote": {
            "tekst": "Gasten willen geen standaard chalet meer. Ze zoeken karakter, een 'wow-factor'. Arcabo snapt dat — hun New Bay en Charleston modellen hebben die Instagrammable uitstraling die parken nodig hebben om de nieuwe generatie gasten aan te trekken.",
            "auteur": "Richard Otten",
            "functie": "Trendwatcher Recreatie & Hospitality",
        },
        "stats": {
            "parken_actief": "150+",
            "jaren_ervaring": "29+",
            "producten_geinstalleerd": "5.000+",
            "klanttevredenheid": "4.7/5",
        },
        "deelname": [
            {"event": "Vakantiebeurs Utrecht 2026", "type": "Exposant"},
            {"event": "Recron Jaarcongres 2025", "type": "Spreker"},
            {"event": "Holiday & Leisure Expo 2025", "type": "Exposant"},
            {"event": "Pleisureworld Summit 2026", "type": "Preferred Partner"},
        ],
        "top_producten": [
            {
                "id": "arcabo-new-bay",
                "name": "New Bay",
                "prijs": 94500,
                "image": "https://arcabo.nl/wp-content/uploads/1-New-Bay-A-buitenzijde-2024.png",
                "reden": "Meest gekozen — Een lust voor het oog, premium afwerking",
                "configuraties": 278,
            },
            {
                "id": "arcabo-charleston",
                "name": "Charleston",
                "prijs": 112000,
                "image": "https://arcabo.nl/wp-content/uploads/1-Charleston-buitenzijde-met-opmaak-1-uitgelicht-klein-2024.png",
                "reden": "Luxe favoriet — Voor de levensgenieters, royale indeling",
                "configuraties": 156,
            },
            {
                "id": "arcabo-ocala",
                "name": "Ocala",
                "prijs": 79950,
                "image": "https://arcabo.nl/wp-content/uploads/Ocala-website-groot-1.png",
                "reden": "Beste prijs/kwaliteit — Eenvoud in levende schoonheid",
                "configuraties": 203,
            },
        ],
        "usps": [
            "Eigen showroom — bezoek onze modellen live",
            "Gratis 3D-ontwerp op maat",
            "Innovatieve productie in Europa",
            "Advies voor recreatieparken door branche-experts",
            "Wintervast en jaarrond bewoonbaar",
            "Seriematig maatwerk mogelijk",
        ],
    },
    "campsolutions": {
        "id": "campsolutions",
        "name": "Campsolutions",
        "tagline": "#1 in Pop-up Campings & Glamping sinds 2008",
        "description": "CampSolutions is expert in het realiseren van belevenisrijke campings en het ontwikkelen van comfortabele glampingtenten. Opgericht in 2008, met het hart van de operatie in Twello. Daar bewaren zij hun voorraad, vervaardigen interieur in eigen werkplaats en voeren reparaties uit in hun eigen naaiatelier. CampSolutions werkt samen met partners als Ten Cate, Vieww en Solvos4Leisure.",
        "website": "https://www.campsolutions.com",
        "logo": "",
        "hero_image": "https://campsolutions.com/wp-content/uploads/2020/12/Scherm%C2%ADafbeelding-2025-12-08-om-15.52.21-min-e1765205821482.png",
        "categorieen": ["glamping", "safaritenten", "lodges", "domes"],
        "pleisureworld_partner": True,
        "pleisureworld_badge": "Glamping Partner",
        "pleisureworld_sinds": "2025",
        "blog_url": "https://www.pleisureworld.nl/blog/campsolutions-glamping-revolutie",
        "blog_titel": "De glamping revolutie: van tent naar beleving",
        "podcast": {
            "titel": "Leisure Talk #16 — Glamping als businessmodel",
            "beschrijving": "Patrick Damen en Dennis Aalders van CampSolutions over de explosieve groei van glamping in Nederland. Hoe zij met maatwerk tenten, eigen naaiatelier en turnkey concepten de markt veroveren. Tips voor ondernemers die willen starten met glamping.",
            "url": "https://www.pleisureworld.nl/podcast/leisure-talk-16",
            "duur": "44 min",
            "gast": "Patrick Damen & Dennis Aalders — Eigenaren CampSolutions",
        },
        "trendwatcher_quote": {
            "tekst": "Glamping is de snelst groeiende sector in de recreatie. Het combineert de charme van kamperen met het comfort dat de moderne gast verwacht. CampSolutions is pionier — hun Wood Lodges en Safari Lodges zetten de standaard voor wat glamping kan zijn.",
            "auteur": "Richard Otten",
            "functie": "Trendwatcher Recreatie & Hospitality",
        },
        "stats": {
            "parken_actief": "80+",
            "jaren_ervaring": "17+",
            "producten_geinstalleerd": "3.000+",
            "klanttevredenheid": "4.5/5",
        },
        "deelname": [
            {"event": "Glamping Show 2025", "type": "Hoofdsponsor"},
            {"event": "Vakantiebeurs Utrecht 2026", "type": "Exposant"},
            {"event": "Recron Jaarcongres 2025", "type": "Partner"},
            {"event": "Pleisureworld Summit 2026", "type": "Glamping Partner"},
        ],
        "top_producten": [
            {
                "id": "camp-wood-lodge",
                "name": "Wood Lodge",
                "prijs": 34950,
                "image": "https://campsolutions.com/wp-content/uploads/2020/12/Scherm%C2%ADafbeelding-2025-12-08-om-15.52.21-min-e1765205821482.png",
                "reden": "Meest gekozen — Unieke beleving, duurzaam hout, snel opbouwbaar",
                "configuraties": 412,
            },
            {
                "id": "camp-safari-lodge",
                "name": "Safari Lodge",
                "prijs": 28500,
                "image": "https://campsolutions.com/wp-content/uploads/2020/12/Scherm%C2%ADafbeelding-2025-12-08-om-15.35.00-min-400x284.png",
                "reden": "Avontuur favoriet — Authentieke safari-ervaring in Nederland",
                "configuraties": 334,
            },
            {
                "id": "camp-panorama-dome",
                "name": "Panorama Dome",
                "prijs": 19950,
                "image": "https://campsolutions.com/wp-content/uploads/2021/12/dof-panorama-uitgelicht-400x284.jpeg",
                "reden": "Instagrammable — Slapen onder de sterren, uniek concept",
                "configuraties": 289,
            },
        ],
        "usps": [
            "Turnkey glamping concepten",
            "Eigen werkplaats en naaiatelier in Twello",
            "Pop-up en permanente oplossingen",
            "Maatwerk tenten naar uw wensen",
            "Samenwerking met Ten Cate (premium tentdoek)",
            "Eigen montageteam voor snelle opbouw",
        ],
    },
    "bbs-systeembouw": {
        "id": "bbs-systeembouw",
        "name": "BBS Systeembouw",
        "tagline": "Maatwerk systeembouw — van idee tot sleutelklare oplevering",
        "description": "BBS Systeembouw uit Heinenoord ontwikkelt, produceert en plaatst hoogwaardige maatwerk woon- en werkoplossingen. Van vakantiewoningen en chalets tot bedrijfsruimtes. Met een 5.0 Google review score en meer dan 100 gerealiseerde projecten is BBS een betrouwbare partner voor recreatieparken die op zoek zijn naar kwaliteit en maatwerk.",
        "website": "https://www.bbssysteembouw.nl",
        "logo": "",
        "hero_image": "https://ucarecdn.com/76932055-baf1-402d-bedb-68e5b903160e/-/format/auto/-/resize/800x500/",
        "categorieen": ["chalets", "vakantiewoningen", "maatwerk"],
        "pleisureworld_partner": False,
        "pleisureworld_badge": "",
        "pleisureworld_sinds": "",
        "blog_url": "https://www.pleisureworld.nl/blog/bbs-systeembouw-maatwerk",
        "blog_titel": "Maatwerk systeembouw: de toekomst van vakantiewoningen",
        "podcast": {
            "titel": "Leisure Talk #19 — Systeembouw als gamechanger",
            "beschrijving": "BBS Systeembouw over hun aanpak van maatwerk modulaire woningen voor recreatie. Hoe zij met een gestructureerde werkwijze van eerste gesprek tot sleutelklare oplevering ontzorgen, en waarom steeds meer parken kiezen voor kwaliteit boven kwantiteit.",
            "url": "https://www.pleisureworld.nl/podcast/leisure-talk-19",
            "duur": "31 min",
            "gast": "BBS Systeembouw Team — Heinenoord",
        },
        "trendwatcher_quote": {
            "tekst": "De recreatiemarkt vraagt om meer dan een standaard chalet. BBS Systeembouw laat zien dat maatwerk niet duur hoeft te zijn als je slim bouwt. Hun 3-stappen aanpak — bespreken, uitwerken, leveren — is een voorbeeld voor de hele branche.",
            "auteur": "Richard Otten",
            "functie": "Trendwatcher Recreatie & Hospitality",
        },
        "stats": {
            "parken_actief": "40+",
            "jaren_ervaring": "20+",
            "producten_geinstalleerd": "100+",
            "klanttevredenheid": "5.0/5",
        },
        "deelname": [
            {"event": "Bouw & Wonen Beurs 2025", "type": "Exposant"},
            {"event": "Recreatie Vakbeurs 2025", "type": "Spreker"},
            {"event": "Pleisureworld Meetup 2026", "type": "Genodigde"},
        ],
        "top_producten": [
            {
                "id": "bbs-comfort",
                "name": "BBS Comfort Vakantiewoning",
                "prijs": 89950,
                "image": "https://ucarecdn.com/16fbc617-c09f-4a02-a022-03d455ad438a/-/format/auto/-/resize/800x500/",
                "reden": "Meest gekozen — Compleet maatwerk, premium afwerking",
                "configuraties": 67,
            },
            {
                "id": "bbs-compact",
                "name": "BBS Compact Chalet",
                "prijs": 64950,
                "image": "https://ucarecdn.com/76932055-baf1-402d-bedb-68e5b903160e/-/format/auto/-/resize/800x500/",
                "reden": "Starter keuze — Betaalbaar maatwerk, snel leverbaar",
                "configuraties": 54,
            },
            {
                "id": "bbs-premium",
                "name": "BBS Premium Woning",
                "prijs": 124500,
                "image": "https://ucarecdn.com/17ae1b5b-9eb9-4c0a-9507-b46fe3a05c33/-/format/auto/-/resize/800x500/",
                "reden": "Luxe segment — Volledig uitgerust, duurzaam",
                "configuraties": 38,
            },
        ],
        "usps": [
            "5.0 Google review score (12 reviews)",
            "Volledig maatwerk — geen standaard prefab",
            "Van ontwerp tot sleutelklare oplevering",
            "3D presentatie van uw ontwerp",
            "Eigen werkplaats in Heinenoord",
            "Ondersteuning bij vergunningsaanvraag",
        ],
    },
}


@partner_router.get("/profiles")
async def get_all_profiles():
    """Alle leveranciersprofielen (summary)."""
    return [
        {
            "id": p["id"],
            "name": p["name"],
            "tagline": p["tagline"],
            "hero_image": p["hero_image"],
            "categorieen": p["categorieen"],
            "pleisureworld_partner": p["pleisureworld_partner"],
            "pleisureworld_badge": p["pleisureworld_badge"],
        }
        for p in PARTNER_PROFILES.values()
    ]


@partner_router.get("/profiles/{partner_id}")
async def get_partner_profile(partner_id: str):
    """Gedetailleerd leveranciersprofiel."""
    profile = PARTNER_PROFILES.get(partner_id)
    if not profile:
        return {"error": "Partner niet gevonden"}
    return profile
